const SITE='';
const SS=['yb','gb','cssbb'], QQ=['cqia','cqi','cqt','cqpa','cqa','cqe','cmqoe'];
const CODE={yb:'CSSYB',gb:'CSSGB',cssbb:'CSSBB',cqia:'CQIA',cqi:'CQI',cqt:'CQT',cqpa:'CQPA',cqa:'CQA',cqe:'CQE',cmqoe:'CMQ/OE'};
const SHORT={yb:'Yellow Belt',gb:'Green Belt',cssbb:'Black Belt',cqia:'Improvement Assoc.',cqi:'Inspector',cqt:'Technician',cqpa:'Process Analyst',cqa:'Auditor',cqe:'Engineer',cmqoe:'Manager'};
const BANK={cqa:50,gb:50,yb:50,cqt:50,cqi:50,cqia:50,cqpa:50};
const BOOKS={cqa:['B0HHS83XSR','B0HHSBCBMK'],gb:['B0HHWPV2ZG','B0HHXJWX75'],yb:['B0HHYTG9PM','B0HHS8N9NF'],
             cqt:['B0HHSSWV2W','B0HHZGYPHR'],cqi:['B0HL54X3T9','B0HHZK1QXP']};
/* Calculator -> exams. */
const MAP={
  pareto:['yb','gb','cssbb','cqe','cqa','cqt','cqpa','cqia','cmqoe','cqi'],
  spc:['yb','gb','cssbb','cqe','cqa','cqi','cqt','cqpa','cqia','cmqoe'],
  constants:['gb','cssbb','cqe','cqi','cqt','cqpa'],
  capability:['gb','cssbb','cqe','cqa','cqi','cqt','cqpa','cqia','cmqoe'],
  sigma:['yb','gb','cssbb','cqe','cqpa','cmqoe'],
  yield:['yb','gb','cssbb','cqe','cqpa','cmqoe'],
  grr:['yb','gb','cssbb','cqe','cqi','cqt','cqpa','cmqoe'],
  grrcpk:['gb','cssbb','cqe','cqi','cqt','cqpa'],
  linearity:['yb','gb','cssbb','cqe','cqi','cqt','cqpa'],
  samplesize:['gb','cssbb','cqe','cqa','cqi','cqt','cqpa','cmqoe'],
  oc:['cssbb','cqe','cqa','cqi','cqt','cqpa'],
  hypothesis:['yb','gb','cssbb','cqe','cqpa']
};
const SIMS=[
  {id:'ql-2207',name:'QL-2207 · The Burr That Nobody Could See',desc:'A customer complaint where the paperwork says the system is healthy and the floor says otherwise. Containment due in 24 hours.'},
  {id:'gp-3318',name:'GP-3318 · Two Numbers That Cannot Both Be Right',desc:'Your capability study says Cpk 1.74. The customer measures 0.69 on the same part. Find out why.'}
];
const SIM_FOR=['yb','gb','cssbb','cqe','cqa','cqi','cqt','cqpa','cqia','cmqoe'];


/* Tool page -> exams whose Body of Knowledge it supports. */
const ALLX=['yb','gb','cssbb','cqia','cqi','cqt','cqpa','cqa','cqe','cmqoe'];
const TOOL_EX={
 'dmaic-roadmap':['yb','gb','cssbb','cqia','cqpa','cqe','cmqoe','cqa','cqi','cqt'],
 'six-sigma-roles-raci':['yb','gb','cssbb','cmqoe','cqpa'],
 'team-development-stages':['yb','gb','cssbb','cqia','cqpa','cmqoe','cqa'],
 'multivoting-nominal-group-technique':['yb','gb','cssbb','cqia','cqpa','cmqoe'],
 'eight-wastes-waste-walk':['yb','gb','cssbb','cqia','cqpa','cqe','cmqoe','cqa','cqi','cqt'],
 'voc-ctq-tree':['yb','gb','cssbb','cqia','cqpa','cqe','cmqoe'],
 'project-selection-matrix':['yb','gb','cssbb','cmqoe','cqpa'],
 'stakeholder-analysis':['yb','gb','cssbb','cmqoe','cqpa'],
 'sipoc':['yb','gb','cssbb','cqia','cqpa','cqa','cmqoe'],
 'project-charter':['yb','gb','cssbb','cmqoe','cqpa'],
 'communication-plan':['yb','gb','cssbb','cmqoe','cqpa'],
 'wbs-gantt-chart':['yb','gb','cssbb','cqe','cmqoe','cqpa'],
 'dmaic-phase-review-checklist':['yb','gb','cssbb'],
 'basic-statistics':['yb','gb','cssbb','cqia','cqi','cqt','cqpa','cqa','cqe','cmqoe'],
 'data-collection-plan':['yb','gb','cssbb','cqia','cqi','cqt','cqpa','cqa','cqe','cmqoe'],
 'msa-accuracy-precision':['yb','gb','cssbb','cqi','cqt','cqpa','cqe','cmqoe'],
 'fishbone-5-whys':ALLX,
 'fmea':['yb','gb','cssbb','cqt','cqpa','cqa','cqe','cmqoe','cqi'],
 'corrective-action-capa':ALLX,
 'distribution-explorer':['yb','gb','cssbb','cqi','cqt','cqpa','cqe','cmqoe','cqa'],
 'correlation-regression':['yb','gb','cssbb','cqpa','cqe','cqi','cqt','cqa'],
 'kaizen-pdca-planner':['yb','gb','cssbb','cqia','cqpa','cqe','cmqoe','cqa','cqi','cqt'],
 'cost-benefit-payback':['yb','gb','cssbb','cqe','cmqoe'],
 'control-plan':['yb','gb','cssbb','cqt','cqpa','cqe'],
 'work-instruction-sop':['yb','gb','cssbb','cqia','cqi','cqt','cqa','cmqoe','cqpa'],
 'strategic-plan-builder':['cmqoe'],
 'swot-pestle-analysis':['cmqoe','cqpa'],
 'hoshin-x-matrix':['cmqoe'],
 'balanced-scorecard':['cmqoe'],
 'change-management-plan':['cmqoe','cqpa'],
 'ethics-compliance-decision-guide':['cqa','cmqoe','cqt','cqpa'],
 'financial-analysis-npv-irr':['cmqoe'],
 'management-review':['cqa','cmqoe'],
 'lessons-learned-register':['cmqoe','cqpa'],
 'cost-of-quality':['cqia','cqa','cmqoe','cqt','gb','cqi','cqpa'],
 'constraints-oee':['cmqoe'],
 'customer-value-segmentation':['cmqoe'],
 'qfd-house-of-quality':['cssbb','cmqoe','gb','cqpa'],
 'supplier-scorecard':['cqpa','cqa','cmqoe'],
 'training-needs-skills-matrix':['cqpa','cmqoe'],
 'training-plan-kirkpatrick':['cqpa','cmqoe'],
 'value-stream-map-takt':['gb','cssbb','cqa','cqi','cqt','cmqoe','cqpa'],
 'kano-model':['gb','cssbb','cmqoe','cqpa'],
 'confidence-interval-calculator':['gb','cssbb','cqe','cqpa','cqt'],
 'attribute-capability':['gb','cssbb','cqe','cqpa'],
 'multi-vari-chart':['gb','cssbb','cqpa'],
 't-test-calculator':['gb','cssbb','cqe','cqpa'],
 'chi-square-proportions-test':['gb','cssbb','cqe'],
 'one-way-anova':['gb','cssbb','cqe'],
 'full-factorial-doe':['gb','cssbb','cqe','cqpa'],
 'smed-setup-reduction':['gb','cssbb','cmqoe','cqpa'],
 'audit-plan-schedule':['cqa','cqt','cqi','cqpa'],
 'process-audit-turtle-diagram':['cqa','cqt','cqi'],
 'audit-checklist-working-papers':['cqa','cqt','cqi','cqpa'],
 'audit-sampling-plan':['cqa','cqt','cqi','cqpa'],
 'audit-nonconformity-report':['cqa','cqt','cqi','cqpa'],
 'audit-car-verification-tracker':['cqa','cqt','cqi','cqpa'],
 'auditor-competence-evaluation':['cqa'],
 'audit-program-risk-schedule':['cqa'],
 'audit-program-metrics':['cqa'],
 'drawing-title-block-tolerance-reader':['cqi','cqt','cqpa'],
 'gdt-position-tolerance':['cqi','cqt','cqe'],
 'tolerance-stack-up':['cqi','cqt','cqe'],
 'gauge-resolution-10-to-1':['cqi','cqt'],
 'cqt-measurement-uncertainty-budget':['cqt','cqi','cqe'],
 'sine-bar-height-gauge-record':['cqi','cqt'],
 'cqt-calibration-oot-impact':['cqt','cqi'],
 'calibration-interval-adjustment':['cqt','cqi'],
 'first-article-inspection':['cqi','cqt','cqpa'],
 'attribute-inspection-defect-classification':['cqi','cqt'],
 'cqt-nonconforming-material-disposition':['cqt','cqi','cqpa'],
 'cqt-reliability-mtbf-calculator':['cqe','cmqoe','cqpa'],
 'flowchart-swimlane':ALLX,
 'activity-network-critical-path':['cssbb','cqpa','cqe','cmqoe'],
 'risk-register-heat-map':['cssbb','cqpa','cqe','cmqoe'],
 'fault-tree-analysis':['cssbb','cqe'],
 'probability-calculator':['gb','cssbb','cqpa','cqe'],
 'affinity-diagram':['cssbb','cqpa','cqe','cmqoe'],
 'interrelationship-digraph':['cssbb','cqpa','cqe','cmqoe'],
 'process-decision-program-chart':['cssbb','cqpa','cqe','cmqoe'],
 'matrix-diagram':['cssbb','cqpa','cqe','cmqoe'],
 'force-field-analysis':['cqe','cmqoe'],
 'kanban-sizing-calculator':['gb','cssbb','cqpa','cqe'],
 'five-s-audit-scorecard':['yb','gb','cssbb','cqia','cqpa','cqe'],
 'error-proofing-poka-yoke':['gb','cssbb','cqia','cqpa','cqe'],
 'standardized-work-combination-sheet':['gb','cssbb','cqe'],
 'heijunka-leveling':['cssbb'],
 'spaghetti-diagram':['cssbb','cqpa'],
 'supplier-selection-matrix':['cqpa','cqe','cmqoe'],
 'ppap-qualification-plan':['cqpa','cqe'],
 'supplier-classification-lifecycle':['cqpa','cqe','cmqoe'],
 'kraljic-portfolio-matrix':[],
 'engineering-change-impact-checklist':['cqpa','cqe'],
 '8d-report':['cqpa','cqe'],
 'is-is-not-problem-specification':['cqe','cssbb'],
 'a3-problem-solving-report':['cssbb','cqpa','cqe'],
 'out-of-control-action-plan':['cqpa','cqe','cssbb','gb'],
 'benchmarking-gap-analysis':['cqpa','cqe','cssbb','cmqoe'],
 'hazard-analysis-risk-control':['cqe'],
 'iq-oq-pq-validation-protocol':['cqe','cqpa'],
 'requirements-traceability-matrix':['cqe'],
 'alcoa-plus-data-integrity-checklist':['cqpa'],
 'lot-traceability-genealogy':['cqpa','cqe'],
 'complaint-reportability-decision-guide':['cqe'],
 'shelf-life-accelerated-aging':[],
 'alert-action-levels':[],
 'meeting-agenda-action-log':['cqpa','cssbb','cqe','cqia'],
 'customer-survey-designer-analyzer':['cqpa','cqe','cssbb','cqia','cmqoe'],
 'gemba-walk-daily-huddle-board':['cssbb','cqe'],
 'design-review-dfx-checklist':['cqe','cssbb'],
 'kpi-dashboard-builder':['cqe','cssbb','cmqoe'],
 'audit-opening-closing-meeting':['cqa','cqpa','cqe'],
 'attribute-agreement-analysis':['cssbb','cqe','gb'],
 'taguchi-loss-function':['cqpa','cssbb'],
 'variables-sampling-plan':['cqe','cqpa','cqi'],
 'probability-plot-stem-leaf-dot-plot':['cqe','cssbb','cqpa','gb'],
 'time-series-moving-average':['cqe','cssbb'],
 'make-buy-analysis':[],
 'supplier-quality-agreement-checklist':[],
 'supplier-onboarding-checklist':[]
};
/* Tools beyond the Yellow Belt set, in hub order (filled in by build_resources.py from tools_content.GROUPS). */
const MQ_TOOLS=EXTRA_SLUGS;
